version: "2.2"
services:
  mysql-binlogsvr:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/workec/mysql_binlogsvr:1.1.3
    volumes:
      - maxwellgraylog_db_data:/var/lib/mysql
    environment:
      DBINSTANCE_ID: rm-bp19t9it7c2998633
      START_TIME: '2018-01-22 14:00:00'
      END_TIME: '2018-01-22 15:00:00'
      ACCESS_ID: LTAIXKHm0v6ob5P4
      ACCESS_SECRET: F7gP************YNll19no
      MYSQL_ROOT_PASSWORD: strongpassword

  maxwell-svr:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/workec/maxwell_graylog:1.1.3
    depends_on:
      - mysql-binlogsvr
    environment:
      producer: kafka
      MYSQL_HOST:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST_GIT: db_crm_shard3
      include_dbs:
      include_tables: t_eccrm_detail
      include_column_values:
      exclude_columns:
      init_position:
      rabbitmq_host:
      rabbitmq_virtual_host:
      rabbitmq_user:
      rabbitmq_pass:
      kafka_server: "172.16.0.84:9092,172.16.0.90:9092"
      kafka_producer_partition_by: database
      MAXWELL_OPTS: "--output_binlog_position=true "
    volumes:
      - maxwellgraylog_db_data:/var/lib/mysql
    links:
      - mysql-binlogsvr:mysql_binlogsvr
volumes:
  maxwellgraylog_db_data: